
version: 2

sources:
  - name: pizza
    tables:
      - name: order_details
      - name: orders
      - name: pizza_types
      - name: pizzas

models:
  - name: Vw_Large_Pepperoni_ByYearandMonth
    description: "Aggregates count of large pepperoni orders by year and month of order date"
    docs:
      show: true
    columns:
        - name: year
          description: "Year of order date"
        - name: month
          description: "Month of order date"
        - name: totalorders
          description: "total orders of large pepperoni pizzas"
  - name: Vw_Medium_Pepperoni_ByYearandMonth
    description: "Aggregates count of medium pepperoni orders by year and month of order date"
    docs:
      show: true
    columns:
        - name: year
          description: "Year of order date"
        - name: month
          description: "Month of order date"
        - name: totalorders
          description: "total orders of medium pepperoni pizzas"
  - name: Vw_Small_Pepperoni_ByYearandMonth
    description: "Aggregates count of medium pepperoni orders by year and month of order date"
    docs:
      show: true
    columns:
      - name: year
        description: "Year of order date"
      - name: month
        description: "Month of order date"
      - name: totalorders
        description: "total orders of small pepperoni pizzas"
  - name: Vw_All_Hawaiian_Orders
    description: "All hawaiian orders"
    docs:
      show: true
    columns:
      - name: order_id
        description: "Primary key of table"
      - name: date
        description: "date of order"
      - name: time
        description: "time of order"